
CREATE TABLE BUYINFO (
    
    BUYCODE NUMBER(4) CONSTRAINT BINFO_BCODE_PK PRIMARY KEY,
    BUYQTY INTEGER CONSTRAINT BINFO_BQTY_NN NOT NULL,
    TOTALPRICE INTEGER CONSTRAINT BINFO_TPRICE_NN NOT NULL,
    ITEMCODE NUMBER CONSTRAINT BINFO_ICODE_FK REFERENCES PRODUCTINFO(ITEMCODE) --참조코드
    
);

CREATE SEQUENCE BINFO_BCODE_SEQ
START WITH 1
INCREMENT BY 1;

SELECT * FROM BUYINFO;
DROP TABLE BUYINFO;