
CREATE TABLE PRODUCTINFO (

    ITEMCODE NUMBER(4) CONSTRAINT PINFO_ICODE_PF PRIMARY KEY,
    NAME VARCHAR2(20) CONSTRAINT PINFO_NAME_NN NOT NULL,
    PRICE INTEGER CONSTRAINT PINFO_PRICE_NN NOT NULL,
    ITEMQTY INTEGER

);
insert into PRODUCTINFO (ITEMCODE,ITEMQTY)values (PINFO_ICODE_SEQ.NEXTVAL ,2);

CREATE TABLE BUYINFO (
    
    BUYCODE NUMBER(4) CONSTRAINT BINFO_BCODE_PK PRIMARY KEY,
    BUYQTY INTEGER CONSTRAINT BINFO_BQTY_NN NOT NULL,
    TOTALPRICE INTEGER CONSTRAINT BINFO_TPRICE_NN NOT NULL,
    ITEMCODE NUMBER CONSTRAINT BINFO_ICODE_FK REFERENCES PRODUCTINFO(ITEMCODE) --참조코드
    
);


select* from PRODUCTINFO;

CREATE SEQUENCE BINFO_BCODE_SEQ
START WITH 1
INCREMENT BY 1;

SELECT * FROM BUYINFO;
DROP TABLE BUYINFO;

CREATE SEQUENCE PINFO_ICODE_SEQ
START WITH 1
INCREMENT BY 1;

select * from PRODUCTINFO P ,BUYINFO b where  p.ITEMCODE = b.ITEMCODE;

INSERT INTO BUYINFO VALUES (BINFO_BCODE_SEQ.NEXTVAL, '콜라', 700, 1);
drop SEQUENCE PINFO_ICODE_SEQ;

INSERT INTO PRODUCTINFO VALUES (PINFO_ICODE_SEQ.NEXTVAL, '콜라', 700, 1);
INSERT INTO PRODUCTINFO VALUES (PINFO_ICODE_SEQ.NEXTVAL, '사이다', 800, 1);
INSERT INTO PRODUCTINFO VALUES (PINFO_ICODE_SEQ.NEXTVAL, '마운틴듀', 600, 1);

select * from PRODUCTINFO where itemcode = ?;
SELECT * FROM PRODUCTINFO;

<<<<<<< Updated upstream
drop table PRODUCTINFO;



select name,ITEMQTY,PRICE from PRODUCTINFO where itemcode = 1 and  ItemQty = 1;
=======

CREATE TABLE BUYINFO (
    
    BUYCODE NUMBER(4) CONSTRAINT BINFO_BCODE_PK PRIMARY KEY,
    BUYQTY INTEGER CONSTRAINT BINFO_BQTY_NN NOT NULL,
    TOTALPRICE INTEGER CONSTRAINT BINFO_TPRICE_NN NOT NULL,
    ITEMCODE NUMBER CONSTRAINT BINFO_ICODE_FK REFERENCES PRODUCTINFO(ITEMCODE) --참조코드
    
);

CREATE SEQUENCE BINFO_BCODE_SEQ
START WITH 1
INCREMENT BY 1;

SELECT * FROM BUYINFO;
DROP TABLE BUYINFO;
drop SEQUENCE BINFO_BCODE_SEQ;
update BUYINFO set itemQty=itemQty+? where itemcode=?;

INSERT INTO BUYINFO VALUES (BINFO_BCODE_SEQ.NEXTVAL,20,14000,1);
INSERT INTO BUYINFO VALUES (BINFO_BCODE_SEQ.NEXTVAL,5,3000,2);
INSERT INTO BUYINFO VALUES (BINFO_BCODE_SEQ.NEXTVAL,2,12000,4);

select p.itemcode,p.name, b.buyqty, b.totalprice from PRODUCTINFO p, BUYINFO b where p.itemcode=b.itemcode;
select p.itemcode,p.name, b.buyqty, b.totalprice 
from PRODUCTINFO p, BUYINFO b 
where p.itemcode=b.itemcode and p.itemcode = '1';

order by b.totalprice desc;

drop SEQUENCE BINFO_BCODE_SEQ;

drop TABLE BUYINFO;
>>>>>>> Stashed changes

commit;